---
title: "Primer parcial"
format: 
    html: 
        toc: true
        number-sections: true
        html-math-method: katex
jupyter: python3
---

# Primer parcial

::: {#exr-primero}
## Python básico

Crear una función que devuelva tres arrays o listas, para el tiempo y para las posiciones $x$ e $y$ 
en el plano de un cuerpo que se mueve bajo condiciones iniciales arbiatrarias con aceleración constante ($a_x$,$a_y$,$v_x$,$v_y$,$x_0$,$y_0$,$\Delta t$).
:::

::: {#exr-segundo}
## Pandas y numpy

Dadas las condiciones iniciales que recibió en papel genere un dataframe con valores creados con la función anterior para el tiempo de vuelo del cuerpo y guardelo como .csv.
:::

::: {#exr-tercero}
## Matplotlib

Importe los datos del csv y haga gráficas $x(t)$, $y(t)$, $v_x(t)$, $v_y(t)$ e $y(x)$ que incluyan los nombres de los ejes con sus rótulos respctivos.
:::

::: {#exr-extra}
## Matplotlib y animaciones

Haga una animación de la gráfica $y(x)$ para el tiempo de vuelo.
:::

Una pista de como encarar el último punto se puede ver a continuación 
(este código tal cual como está no corre, pero les puede servir de ayuda)
